[project]
name = "pycondor-job-submission-template"
version = "0.1.0"
description = ""
authors = [
    {name = "wyhwong",email = "wyhwong@link.cuhk.edu.hk"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pycondor (>=0.6.1,<0.7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
